services:
  mysql:
    image: mysql:8.0
    container_name: cop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: copdb
      MYSQL_USER: copuser
      MYSQL_PASSWORD: coppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7
    container_name: cop-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cop-rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./Backend
    container_name: cop-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/copdb?useUnicode=true&characterEncoding=utf8&serverTimezone=America/Bogota&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: copuser
      SPRING_DATASOURCE_PASSWORD: coppass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./Worker
    container_name: cop-worker
    restart: unless-stopped
    environment:
      SERVER_PORT: 8082
      worker.backend.base-url: http://backend:8080/api
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/workerdb
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      # Opcional correo (configurar si se desea env√≠o real)
      # SPRING_MAIL_HOST: smtp.gmail.com
      # SPRING_MAIL_PORT: 587
      # SPRING_MAIL_USERNAME: ""
      # SPRING_MAIL_PASSWORD: ""
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      # SPRING_MAIL_FROM: ""
    depends_on:
      - backend
      - mongo
      - rabbitmq
    # No exponemos puerto del worker, no es necesario acceso externo

  dashboard:
    build:
      context: ./DashBoard-COP
    container_name: cop-dashboard
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8085:80"

  cop:
    build:
      context: ./COP
    container_name: cop-cop
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8086:80"

volumes:
  mysql_data:
  mongo_data:

